#!/bin/bash

# Project is automatically generated by maven, which is why it has such a deep subpaths 
# use this script to go to the course_scheduling folder automatically 
# don't forget chmod 755 in case you don't have the permission to run this script 

cd main/java/com/course_scheduling/